# Generated by Django 2.0.2 on 2018-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='atendees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
