# Generated by Django 2.0.2 on 2018-06-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reports_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
