# Generated by Django 2.0.2 on 2018-05-21 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldToNumber', models.CharField(max_length=10)),
                ('soldToName', models.CharField(max_length=80)),
                ('shipToNumber', models.CharField(max_length=10)),
                ('shipToName', models.CharField(max_length=80)),
                ('shipToCity', models.CharField(max_length=80)),
                ('shipToCountry', models.CharField(max_length=80)),
                ('products', models.CharField(max_length=80)),
                ('sellerNumber', models.CharField(max_length=10)),
                ('sellerName', models.CharField(max_length=80)),
                ('cmscNumber', models.CharField(max_length=10)),
                ('cmscName', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesrep_number', models.IntegerField(blank=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerName', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.Groups'),
        ),
    ]
