# Generated by Django 2.0.2 on 2018-05-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='name',
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
