# Generated by Django 2.0.2 on 2018-05-16 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesapp', '0002_auto_20180516_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesrep_number', models.IntegerField(blank=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerName', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
