# Generated by Django 2.0.2 on 2018-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
